### ISSUE TITLE
img element tag has no close symbol

### ISSUE THREAD

**Issue by EvenAmongTheStars** [Zaczero/bootstrap-v4-snippets#19]
For example,
b4 card group generate a snippets:
```
        <div class="card-group">
          <div class="card">
            <img class="card-img-top" data-src="holder.js/100x180/" alt="Card image cap">
            <div class="card-body">
              <h4 class="card-title">Title</h4>
              <p class="card-text">Text</p>
            </div>
          </div>
          <div class="card">
            <img class="card-img-top" data-src="holder.js/100x180/" alt="Card image cap">
            <div class="card-body">
              <h4 class="card-title">Title</h4>
              <p class="card-text">Text</p>
            </div>
          </div>
        </div>
```
the image element tag has no close symbol "/" at the end like this:
`<img class="card-img-top" data-src="holder.js/100x180/" alt="Card image cap"/>`

It will cause some problems in JSX.

**Comment by Zaczero** [comment]
`<img>` is an HTML void tag which means that it doesn't require a slash at the end. And because they are optional I think we should keep it simple as it is _(without the slash)_. On the bootstrap documentation they don't use those end slashes neither.

I do understand that it `cause some problems in JSX` as you said but this is just a little odd to me that some HTML supporting language cannot handle img tags without end slash properly. Maybe try changing the config of your project or something like that?

If we add those end slashes there is a same chance that another guy will come and post a compatibility issue because he needs snippets without the img slashes at the end. There is no perfect solution for that.

I suggest you two solutions _(first one is easier)_:
* Copy snippets file from [here](https://github.com/Zaczero/bootstrap-v4-snippets/blob/master/bootstrap-v4-snippets/snippets/snippets.json), modify them for your own needs and then paste them to `VS Code > F1 > Preferences: Configure User Snippets > LANGUAGE.json` and save.
* As a second solution I suggest you to fork this repository, make the changes, compile it and install in Visual Studio Code.
